[package]
name = "tool"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
custom-utils = { version = "0.11", features = ["daemon-async"] }
reqwest = { version = "0.13", default-features = false, features = ["json"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
default = []
prod = ["custom-utils/prod"]
